name: publish-docker

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build image
      run: docker buildx build . --tag "swiftnav/proxpi:${{ github.ref_name }}"
    - name: Run unit-tests in image
      run: docker run
        --rm
        --volume "$(pwd)/tests:/srv/tests"
        --entrypoint ''
        "swiftnav/proxpi:${{ github.ref_name }}"
        sh -c 'pip install --requirement /srv/tests/requirements.txt
        && pytest -vvra /srv/tests'
    - name: Run image test
      run: tests/test-docker-image.sh "${{ github.ref_name }}"
    - name: Login to DockerHub
      run: >
        echo ${{ secrets.DOCKERHUB_PASSWORD }}
        | docker login --password-stdin -u swiftnav
    - name: Publish image
      run: docker push "swiftnav/proxpi:${{ github.ref_name }}"
    - name: Check tag
      id: check-tag
      run: |
        if [[ "${{ github.ref_name }}" =~ '^v\d+\.\d+\.\d+$' ]]; then
            echo ::set-output name=match::true
        fi
    - name: Publish latest image
      if: steps.check-tag.outputs.match == 'true'
      run: |
        docker tag "swiftnav/proxpi:${{ github.ref_name }}" swiftnav/proxpi:latest
        docker push swiftnav/proxpi:latest
